// Generated by @hypernym/nuxt-gsap
import { Plugin } from '#app';
import { gsap } from 'gsap';
import { Flip } from 'gsap/Flip';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ScrollToPlugin } from 'gsap/ScrollToPlugin';
import { Draggable } from 'gsap/Draggable';
declare const plugin: Plugin<{
  gsap: typeof gsap;
  Flip: typeof Flip;
ScrollTrigger: typeof ScrollTrigger;
ScrollToPlugin: typeof ScrollToPlugin;
Draggable: typeof Draggable;
}>;
export default plugin;