// Generated by @hypernym/nuxt-gsap
import { defineNuxtPlugin } from '#app';
import { gsap } from 'gsap';
import { Flip } from 'gsap/Flip';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ScrollToPlugin } from 'gsap/ScrollToPlugin';
import { Draggable } from 'gsap/Draggable';
const plugin = defineNuxtPlugin(() => {
  if(process.client) {
  gsap.registerPlugin(Flip,ScrollTrigger,ScrollToPlugin,Draggable);
  
  
}
  return {
    provide: {
      gsap,
      Flip,
ScrollTrigger,
ScrollToPlugin,
Draggable
    }
  }
})
export default plugin;