// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/10/2024, 8:43:47 AM
const configMerger = require("C:/Users/Terada/web-mms/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Terada/web-mms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/icons/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/plugins/**/*.{js,ts,mjs}","C:/Users/Terada/web-mms/composables/**/*.{js,ts,mjs}","C:/Users/Terada/web-mms/utils/**/*.{js,ts,mjs}","C:/Users/Terada/web-mms/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Terada/web-mms/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/Terada/web-mms/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
